CREATE DATABASE QuanLyGiaoVu;
USE QuanLyGiaoVu;

CREATE TABLE Khoa(
	MaKhoa VARCHAR(4) NOT NULL,
	TenKhoa VARCHAR(40),
	NgTLap SMALLDATETIME,
	TrgKhoa CHAR(4),

	CONSTRAINT PK_MaKhoa PRIMARY KEY (MaKhoa),
);

CREATE TABLE MonHoc(
	MaMH VARCHAR(10) NOT NULL,
	TenMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MaKhoa VARCHAR(4),

	CONSTRAINT PK_MaMH PRIMARY KEY (MaMH),
	CONSTRAINT PK_Khoa_MonHoc FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa),
);

CREATE TABLE DieuKien(
	MaMH VARCHAR(10),
	MaMH_Truoc VARCHAR(10),

	CONSTRAINT PK_MaMH PRIMARY KEY (MaMH, MaMH_Truoc),
	CONSTRAINT PK_Khoa_DieuKien FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH),
	CONSTRAINT PK_Khoa_DieuKien_Truoc FOREIGN KEY (MaMH_Truoc) REFERENCES MonHoc(MaMH),
);

CREATE TABLE GiaoVien(
	MaGV CHAR(4),
	HoTen VARCHAR(40),
	HocVi VARCHAR(10),
	HocHam VARCHAR(10),
	GioiTinh VARCHAR(3),
	NgSinh SMALLDATETIME,
	NgVL SMALLDATETIME,
	HeSo NUMERIC(4, 2),
	MucLuong MONEY,
	MaKhoa VARCHAR(4),

	CONSTRIAINT
);

CREATE TABLE Lop(
	MaLop CHAR(3),
	TenLop VARCHAR(40),
	TrgLop CHAR(5),
	SiSo TINYINT,
	MaGVCN CHAR(4),
);

USE master;
DROP DATABASE QuanLyGiaoVu;